export const GET_PRODUCTS = 'GET_PRODUCTS'
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS'
export const GET_PRODUCTS_FAILURE = 'GET_PRODUCTS_FAILURE'
export const ADD_PRODUCT_TO_WISH = 'ADD_PRODUCT_TO_WISH'
export const ADD_TO_WISH = 'ADD_TO_WISH';
