export const GET_PRODUCTS_FROM_SEARCH = 'GET_PRODUCTS_FROM_SEARCH';
export const GET_PRODUCTS_FROM_SEARCH_SUCCESS = 'GET_PRODUCTS_FROM_SEARCH_SUCCESS';
export const GET_PRODUCTS_FROM_SEARCH_FAILURE = 'GET_PRODUCTS_FROM_SEARCH_FAILURE';
